# Generated by Django 4.2.14 on 2024-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
    ]
